// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pl'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	HEADER: {
		/**
		 * Z​a​m​k​n​i​j​ ​n​a​w​i​g​a​c​j​ę
		 */
		CLOSE_NAVIGATION: string
		/**
		 * O​t​w​ó​r​z​ ​n​a​w​i​g​a​c​j​ę
		 */
		OPEN_NAVIGATION: string
	}
	/**
	 * C​z​e​ś​ć​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
}

export type TranslationFunctions = {
	HEADER: {
		/**
		 * Zamknij nawigację
		 */
		CLOSE_NAVIGATION: () => LocalizedString
		/**
		 * Otwórz nawigację
		 */
		OPEN_NAVIGATION: () => LocalizedString
	}
	/**
	 * Cześć {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
